
server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yzh
      routes:
        - id: api_route
          uri: http://8.130.68.218:8123
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://172.16.159.71:8848